const assert = require('node:assert/strict');
const api = require('../octoprint_rme_compatibility/static/js/passive_tools.js');
const state = {supported: true, machine: {hotends: 8, tool_capacity: 8}, active_tool: {physical: 3, logical: 0}};
assert(api.isIndx(state));
assert(api.isIndx({supported: true, machine: {hotends: 1, tool_capacity: 8}}));
assert(api.unavailable(state, 'tool7', -1));
assert(api.unavailable(state, 'tool0', null));
assert(!api.unavailable(state, 'tool3', 220));
assert(!api.unavailable(state, 'bed', -1));
assert(!api.unavailable({supported: false, machine: state.machine}, 'tool0', -1));
assert(!api.unavailable({supported: true, machine: {hotends: 5, tool_capacity: 5}}, 'tool0', -1));
const data = [{time: 5, tool0: {actual: -1, target: 120}, tool3: {actual: 220, target: 220}, bed: {actual: 60, target: 60}}];
const graph = api.graphData(state, data);
assert.equal(graph[0].tool0.actual, null);
assert.equal(graph[0].tool0.target, null);
assert.equal(data[0].tool0.actual, -1);
assert.equal(graph[0].tool3.actual, 220);
assert.equal(graph[0].bed.actual, 60);
let sent = 0;
const commands = [];
const vm = {tools: () => [], clearAutosendTarget: () => {},
    rmeSendTemperature: command => { commands.push(command); return {done: cb => cb()}; },
    setTargetToValue: () => ++sent, _processTemperatureData: (time, d) => d};
const template = 'html: formatTemperature(actual()), attr: {title: formatTemperature(actual(), undefined, undefined, true)} submit: function(element)';
const patched = api.install(vm, () => state, x => typeof x === 'function' ? x() : x, template, String, () => 'rejected');
assert(!patched.includes('formatTemperature(actual()'));
assert(patched.includes('visible: !$root.rmePassiveTool($data)'));
const parked = {key: () => 'tool0', actual: () => -1};
assert.equal(vm.rmeTemperatureText(parked), 'Parked / unavailable');
assert.equal(vm.setTargetToValue(parked, 220), 'rejected');
assert.equal(sent, 0);
assert.equal(vm.setTargetToValue(parked, 0), 'rejected');
vm.setTargetToValue({key: 'tool3', actual: 220, newTarget: () => {}}, 215);
vm.setTargetToValue({key: 'chamber', actual: 30, newTarget: () => {}}, 45);
vm.setTargetToValue({key: 'bed', actual: 60}, 70);
assert.equal(sent, 1);
assert.deepEqual(commands, ['M104 S215', 'M141 S45']);
vm.tools = () => [{key: 'tool0', actual: -1}, {key: 'tool3', actual: 215}];
assert.deepEqual(vm.rmeVisibleTools().map(x => x.key), ['tool3']);
state.active_tool.physical = null;
assert.deepEqual(vm.rmeVisibleTools(), []);
assert.equal(vm.setTargetToValue({key: 'tool3', actual: 215}, 220), 'rejected');
assert.equal(vm._processTemperatureData(5, data)[0].tool0.actual, null);
state.supported = false;
assert.equal(vm.rmeTemperatureText(parked), '-1');
vm.setTargetToValue(parked, 220);
assert.equal(sent, 2);
console.log('Passive INDX temperature display/control tests passed');
