const fs = require('node:fs');
const assert = require('node:assert/strict');
const {JSDOM} = require('jsdom');
const {jQueryFactory} = require('jquery/factory');
(async function () {
    const dom = new JSDOM('<html><body></body></html>', {runScripts: 'outside-only'});
    const w = dom.window, $ = jQueryFactory(w);
    w.$ = w.jQuery = $;
    w.eval(fs.readFileSync(require.resolve('knockout/build/output/knockout-latest.js'), 'utf8'));
    w.OCTOPRINT_VIEWMODELS = [];
    w.gettext = x => x;
    w.PNotify = function () {};
    $.fn.modal = function () { return this; };
    w.eval(fs.readFileSync('octoprint_rme_compatibility/static/js/rme_compatibility.js', 'utf8'));
    await new Promise(resolve => $(resolve));
    const vm = new w.OCTOPRINT_VIEWMODELS[0].construct([{}, {}, {}, {}]);
    const template = fs.readFileSync('octoprint_rme_compatibility/templates/rme_compatibility_settings.jinja2', 'utf8');
    const start = template.indexOf('<table class="table table-condensed rme-storage-table"');
    const host = w.document.createElement('div');
    host.innerHTML = '<!-- ko if: settingsStorageExpanded -->' + template.slice(start, template.indexOf('</table>', start) + 8) + '<!-- /ko -->';
    w.document.body.append(host);
    w.ko.applyBindings(vm, host);
    const state = {connected: true, supported: true, storage: {supported: true, entries:
        Array.from({length: 300}, (_, i) => ({name: 'part' + i + '.gcode', type: 'file', size: 1000}))}};
    vm.acceptState(JSON.parse(JSON.stringify(state)));
    assert.equal(host.querySelectorAll('tbody tr').length, 0, 'hidden Settings storage must not render files');
    vm.settingsStorageExpanded(true);
    const first = host.querySelector('tbody tr');
    first.querySelector('button').focus();
    const began = performance.now();
    for (let i = 0; i < 5; i++) vm.acceptState(JSON.parse(JSON.stringify(state)));
    console.log('Five unchanged 300-file snapshots: ' + Math.round(performance.now() - began) + 'ms');
    assert(host.querySelector('tbody tr') === first, 'unchanged polls must retain DOM rows and focus');
    assert(w.document.activeElement === first.querySelector('button'));
    state.storage.entries[299].size = 2000;
    vm.acceptState(JSON.parse(JSON.stringify(state)));
    assert(host.querySelector('tbody tr') === first, 'changing one file must preserve other rows');
    assert(host.textContent.includes('2.0 KiB'));
    vm.settingsStorageExpanded(false);
    assert.equal(host.querySelectorAll('tbody tr').length, 0);
    vm.settingsStorageExpanded(true);
    assert(host.textContent.includes('2.0 KiB'), 'reopening shows current files');
    assert(template.includes('<!-- ko if: settingsStorageExpanded -->'));
    assert(template.includes('<!-- ko if: settingsPrinterExpanded -->'));
    assert(template.includes('<!-- ko if: settingsFirmwareExpanded -->'));
    console.log('Settings list identity and updates passed');
    w.close();
})();
