const fs = require('node:fs');
const assert = require('node:assert/strict');
const {JSDOM} = require('jsdom');
const {jQueryFactory} = require('jquery/factory');
(async function () {
    const dom = new JSDOM('<!doctype html><html><body></body></html>', {runScripts: 'outside-only'});
    const w = dom.window;
    w.$ = w.jQuery = jQueryFactory(w);
    w.eval(fs.readFileSync(require.resolve('knockout/build/output/knockout-latest.js'), 'utf8'));
    w.OCTOPRINT_VIEWMODELS = [];
    w.gettext = x => x;
    w.PNotify = function () {};
    w.eval(fs.readFileSync('octoprint_rme_compatibility/static/js/rme_compatibility.js', 'utf8'));
    await new Promise(resolve => w.$(resolve));
    const vm = new w.OCTOPRINT_VIEWMODELS[0].construct([{}, {}, {}, {}]);
    const commands = [];
    vm.command = (name, data) => commands.push([name, data]);
    vm.state({firmware_releases: {status: 'ready', assets: [{id: '123', name: 'test.bbf', version: '6.10.1-RME', variant: 'coreone_indx', comparison: 'current'}]}});
    assert.match(vm.releaseLabel(vm.releaseAssets()[0]), /checksum matches/);
    vm.selectedRelease('123');
    w.confirm = () => false;
    vm.downloadFirmwareRelease();
    assert.equal(commands.length, 0);
    w.confirm = () => true;
    vm.downloadFirmwareRelease();
    assert.equal(commands[0][0], 'download_firmware_release');
    assert.equal(commands[0][1].id, '123');
    assert.equal(commands.some(c => /flash|stage/.test(c[0])), false);
    vm.state({firmware_releases: {status: 'downloaded', filename: 'verified.bbf'}});
    vm.useDownloadedFirmware();
    assert.equal(vm.selectedFirmware(), 'verified.bbf');
    dom.window.close();
    console.log('Firmware release UI tests passed');
})().catch(error => { console.error(error); process.exit(1); });
